import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const TEST_VAULT_PLUGIN_DIR = "/Users/s-ikari/work/obsidian-realtime-transcribe/test-vault/.obsidian/plugins/obsidian-task-manager";

function copyToTestVault() {
	try {
		if (!fs.existsSync(TEST_VAULT_PLUGIN_DIR)) {
			fs.mkdirSync(TEST_VAULT_PLUGIN_DIR, { recursive: true });
		}
		fs.copyFileSync("main.js", path.join(TEST_VAULT_PLUGIN_DIR, "main.js"));
		fs.copyFileSync("manifest.json", path.join(TEST_VAULT_PLUGIN_DIR, "manifest.json"));
		fs.copyFileSync("styles.css", path.join(TEST_VAULT_PLUGIN_DIR, "styles.css"));
		console.log(`[Build] Successfully copied artifacts to ${TEST_VAULT_PLUGIN_DIR}`);
	} catch (e) {
		console.error("[Build] Failed to copy artifacts to test-vault:", e);
	}
}

const copyPlugin = {
	name: "copy-to-test-vault",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyToTestVault();
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
