/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  taskFolder: "tasks",
  idPrefix: "TASK-",
  defaultStatus: "todo",
  defaultPriority: "medium",
  antigravityCommand: "agy"
};

// src/settings.ts
var import_obsidian = require("obsidian");
var TaskManagerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "JIRA-style Task Manager Settings" });
    new import_obsidian.Setting(containerEl).setName("Task Folder").setDesc("Folder path where 1-task-1-note files are stored (e.g. 'tasks').").addText(
      (text) => text.setPlaceholder("tasks").setValue(this.plugin.settings.taskFolder).onChange(async (value) => {
        this.plugin.settings.taskFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("ID Prefix").setDesc("Prefix used when generating new ticket IDs (e.g. 'TASK-').").addText(
      (text) => text.setPlaceholder("TASK-").setValue(this.plugin.settings.idPrefix).onChange(async (value) => {
        this.plugin.settings.idPrefix = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "AI Copilot Settings (Antigravity CLI)" });
    new import_obsidian.Setting(containerEl).setName("Antigravity Command").setDesc("Executable name or path for Antigravity CLI (default: 'agy').").addText(
      (text) => text.setPlaceholder("agy").setValue(this.plugin.settings.antigravityCommand).onChange(async (value) => {
        this.plugin.settings.antigravityCommand = value.trim() || "agy";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/views/TaskManagerView.ts
var import_obsidian3 = require("obsidian");

// src/services/TaskService.ts
var import_obsidian2 = require("obsidian");
var TaskService = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  /**
   * Get all task notes inside configured folder or vault
   */
  getAllTasks() {
    const folderPath = (0, import_obsidian2.normalizePath)(this.plugin.settings.taskFolder);
    const files = this.app.vault.getMarkdownFiles();
    const tasks = [];
    for (const file of files) {
      if (folderPath && folderPath !== "." && folderPath !== "/") {
        if (!file.path.startsWith(folderPath + "/") && file.path !== folderPath) {
          continue;
        }
      }
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = (cache == null ? void 0 : cache.frontmatter) || {};
      const title = fm.title || file.basename;
      const id = fm.id || file.basename;
      const status = this.normalizeStatus(fm.status);
      const priority = this.normalizePriority(fm.priority);
      tasks.push({
        id,
        title,
        status,
        priority,
        type: fm.type || (fm.parent ? "subtask" : "task"),
        parent: fm.parent || void 0,
        due: fm.due || void 0,
        scheduled: fm.scheduled || void 0,
        assignee: fm.assignee || "",
        epic: fm.epic || "",
        created: fm.created || "",
        updated: fm.updated || "",
        file
      });
    }
    return tasks;
  }
  /**
   * Create a new Task note with standard Frontmatter
   */
  async createTask(title, status = "todo", priority = "medium", options) {
    const folderPath = (0, import_obsidian2.normalizePath)(this.plugin.settings.taskFolder);
    if (folderPath && folderPath !== "." && folderPath !== "/") {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    const existingTasks = this.getAllTasks();
    const nextNumber = existingTasks.length + 1;
    const idStr = `${this.plugin.settings.idPrefix}${String(nextNumber).padStart(3, "0")}`;
    const safeTitle = title.replace(/[\\/:*?"<>|]/g, "_");
    const fileName = `${idStr} ${safeTitle}.md`;
    const filePath = folderPath && folderPath !== "." && folderPath !== "/" ? `${folderPath}/${fileName}` : fileName;
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const taskType = (options == null ? void 0 : options.type) || ((options == null ? void 0 : options.parent) ? "subtask" : "task");
    const frontmatterLines = [
      "---",
      `id: ${idStr}`,
      `title: "${title.replace(/"/g, '\\"')}"`,
      `status: ${status}`,
      `priority: ${priority}`,
      `type: ${taskType}`
    ];
    if (options == null ? void 0 : options.parent)
      frontmatterLines.push(`parent: "${options.parent}"`);
    if (options == null ? void 0 : options.due)
      frontmatterLines.push(`due: "${options.due}"`);
    if (options == null ? void 0 : options.scheduled)
      frontmatterLines.push(`scheduled: "${options.scheduled}"`);
    frontmatterLines.push(
      `created: ${now}`,
      `updated: ${now}`,
      "---",
      "",
      `# ${title}`,
      "",
      "## Description",
      ""
    );
    const newFile = await this.app.vault.create(filePath, frontmatterLines.join("\n"));
    return newFile;
  }
  /**
   * Convenient wrapper to create a subtask under a parent task
   */
  async createSubtask(parentTask, title) {
    return this.createTask(title, "todo", "medium", {
      parent: parentTask.id,
      type: "subtask",
      due: parentTask.due,
      scheduled: parentTask.scheduled
    });
  }
  /**
   * Update task status in Frontmatter
   */
  async updateTaskStatus(file, status) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.status = status;
      fm.updated = (/* @__PURE__ */ new Date()).toISOString();
    });
  }
  /**
   * Update scheduled date and due date
   */
  async updateTaskSchedule(file, scheduled, due) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      if (scheduled !== void 0)
        fm.scheduled = scheduled;
      if (due !== void 0)
        fm.due = due;
      fm.updated = (/* @__PURE__ */ new Date()).toISOString();
    });
  }
  /**
   * Open the task Markdown note in workspace
   */
  async openTaskNote(file) {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file);
  }
  normalizeStatus(status) {
    if (typeof status === "string") {
      const s = status.toLowerCase();
      if (s === "in_progress" || s === "in progress" || s === "doing")
        return "in_progress";
      if (s === "done" || s === "completed")
        return "done";
    }
    return "todo";
  }
  normalizePriority(priority) {
    if (typeof priority === "string") {
      const p = priority.toLowerCase();
      if (p === "low")
        return "low";
      if (p === "high")
        return "high";
      if (p === "highest")
        return "highest";
    }
    return "medium";
  }
};

// src/services/AIService.ts
var import_child_process = require("child_process");
var import_util = require("util");
var os = __toESM(require("os"));
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var execAsync = (0, import_util.promisify)(import_child_process.exec);
function getExtendedEnv() {
  const home = os.homedir();
  const extraPaths = [
    path.join(home, ".local", "bin"),
    path.join(home, ".antigravity", "bin"),
    path.join(home, ".gemini", "antigravity", "bin"),
    "/usr/local/bin",
    "/opt/homebrew/bin",
    "/usr/bin",
    "/bin"
  ];
  const currentPath = process.env.PATH || "";
  const combinedPath = extraPaths.concat(currentPath.split(":")).filter(Boolean);
  const uniquePath = Array.from(new Set(combinedPath)).join(":");
  return {
    ...process.env,
    PATH: uniquePath
  };
}
function resolveCommandPath(command) {
  if (path.isAbsolute(command)) {
    return command;
  }
  const home = os.homedir();
  const searchDirs = [
    path.join(home, ".local", "bin"),
    path.join(home, ".antigravity", "bin"),
    path.join(home, ".gemini", "antigravity", "bin"),
    "/usr/local/bin",
    "/opt/homebrew/bin",
    "/usr/bin",
    "/bin"
  ];
  for (const dir of searchDirs) {
    const fullPath = path.join(dir, command);
    if (fs.existsSync(fullPath)) {
      return fullPath;
    }
  }
  return command;
}
var AIService = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Ask AI (Antigravity CLI) to break down a parent task into subtask titles
   */
  async breakdownTask(task) {
    const prompt = `You are a helpful task manager AI. Break down the task titled "${task.title}" into 3 to 5 concrete action items (subtasks).
Respond ONLY with a valid JSON array of strings representing the subtask titles, for example:
["Gather requirements", "Draft design document", "Review with team"]
Do not include any explanation or markdown code block syntax outside the JSON array.`;
    try {
      const output = await this.runCLI(prompt);
      const parsed = this.extractJSONArray(output);
      if (parsed && parsed.length > 0) {
        return parsed;
      }
    } catch (err) {
      console.warn("[TaskManager AI] CLI execution failed or not found, using smart breakdown fallback:", err);
    }
    return [
      `Research & Plan: ${task.title}`,
      `Implementation: ${task.title}`,
      `Review & Test: ${task.title}`
    ];
  }
  /**
   * Ask AI (Antigravity CLI) to reschedule overdue/unscheduled tasks
   */
  async rescheduleTasks(tasks) {
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const taskSummaries = tasks.map((t) => ({
      id: t.id,
      title: t.title,
      status: t.status,
      due: t.due || "none",
      scheduled: t.scheduled || "none"
    }));
    const prompt = `You are a smart AI task scheduler. Today is ${todayStr}.
Analyze these tasks:
${JSON.stringify(taskSummaries, null, 2)}

For any tasks that are OVERDUE or UNSCHEDULED and not 'done', assign a recommended scheduled date (format YYYY-MM-DD) starting from today or upcoming days.
Respond ONLY with a valid JSON object mapping task IDs to new scheduled date strings, for example:
{
  "TASK-001": "${todayStr}"
}
Do not output any text other than the JSON object.`;
    try {
      const output = await this.runCLI(prompt);
      const parsed = this.extractJSONObject(output);
      if (parsed && Object.keys(parsed).length > 0) {
        return parsed;
      }
    } catch (err) {
      console.warn("[TaskManager AI] CLI execution failed, using smart reschedule fallback:", err);
    }
    const result = {};
    for (const t of tasks) {
      if (t.status !== "done" && (!t.scheduled || t.scheduled < todayStr)) {
        result[t.id] = todayStr;
      }
    }
    return result;
  }
  async runCLI(promptText) {
    const commandName = this.plugin.settings.antigravityCommand || "agy";
    const exePath = resolveCommandPath(commandName);
    const env = getExtendedEnv();
    const escapedPrompt = promptText.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/`/g, "\\`");
    const cmd = `"${exePath}" -p "${escapedPrompt}"`;
    const { stdout } = await execAsync(cmd, {
      env,
      timeout: 25e3,
      maxBuffer: 1024 * 1024 * 5
    });
    return stdout.trim();
  }
  extractJSONArray(text) {
    try {
      const match = text.match(/\[[\s\S]*\]/);
      if (match) {
        const jsonStr = match[0];
        const arr = JSON.parse(jsonStr);
        if (Array.isArray(arr)) {
          return arr.map((item) => String(item));
        }
      }
    } catch (e) {
      console.error("[TaskManager AI] Failed to parse JSON array from output:", text);
    }
    return null;
  }
  extractJSONObject(text) {
    try {
      const match = text.match(/\{[\s\S]*\}/);
      if (match) {
        const jsonStr = match[0];
        const obj = JSON.parse(jsonStr);
        if (typeof obj === "object" && obj !== null) {
          return obj;
        }
      }
    } catch (e) {
      console.error("[TaskManager AI] Failed to parse JSON object from output:", text);
    }
    return null;
  }
};

// src/views/TaskManagerView.ts
var VIEW_TYPE_TASK_MANAGER = "jira-task-manager-view";
var TaskManagerView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.searchFilter = "";
    this.activeViewMode = "status";
    this.eventListeners = [];
    this.isProcessingAI = false;
    this.taskService = new TaskService(this.app, this.plugin);
    this.aiService = new AIService(this.plugin);
  }
  getViewType() {
    return VIEW_TYPE_TASK_MANAGER;
  }
  getDisplayText() {
    return "Task Manager (JIRA)";
  }
  getIcon() {
    return "kanban";
  }
  async onOpen() {
    this.render();
    const ref1 = this.app.vault.on("modify", () => this.render());
    const ref2 = this.app.vault.on("create", () => this.render());
    const ref3 = this.app.vault.on("delete", () => this.render());
    const ref4 = this.app.metadataCache.on("changed", () => this.render());
    this.eventListeners.push(ref1, ref2, ref3, ref4);
  }
  async onClose() {
    for (const ref of this.eventListeners) {
      this.app.vault.offref(ref);
      this.app.metadataCache.offref(ref);
    }
    this.eventListeners = [];
  }
  render() {
    const container = this.containerEl;
    container.empty();
    container.addClass("jira-task-manager-container");
    const headerEl = container.createDiv({ cls: "jira-tm-header" });
    const titleGroup = headerEl.createDiv({ cls: "jira-tm-title-group" });
    titleGroup.createEl("h2", { text: "JIRA Task Board" });
    const switcherEl = titleGroup.createDiv({ cls: "jira-view-switcher" });
    const statusTab = switcherEl.createEl("button", {
      text: "Status Board",
      cls: `jira-tab-btn ${this.activeViewMode === "status" ? "active" : ""}`
    });
    statusTab.addEventListener("click", () => {
      this.activeViewMode = "status";
      this.render();
    });
    const scheduleTab = switcherEl.createEl("button", {
      text: "Schedule Board",
      cls: `jira-tab-btn ${this.activeViewMode === "schedule" ? "active" : ""}`
    });
    scheduleTab.addEventListener("click", () => {
      this.activeViewMode = "schedule";
      this.render();
    });
    const createForm = headerEl.createDiv({ cls: "jira-tm-create-form" });
    const titleInput = createForm.createEl("input", {
      type: "text",
      placeholder: "What needs to be done?...",
      cls: "jira-tm-input"
    });
    const createBtn = createForm.createEl("button", {
      text: "+ Create Task",
      cls: "mod-cta jira-tm-btn"
    });
    const submitTask = async () => {
      const text = titleInput.value.trim();
      if (!text)
        return;
      titleInput.value = "";
      const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      await this.taskService.createTask(text, "todo", "medium", { scheduled: todayStr });
      this.render();
    };
    createBtn.addEventListener("click", submitTask);
    titleInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        submitTask();
      }
    });
    const controlsEl = headerEl.createDiv({ cls: "jira-tm-controls" });
    const aiRescheduleBtn = controlsEl.createEl("button", {
      text: "\u{1F504} AI Reschedule",
      cls: "jira-tm-btn-ai"
    });
    aiRescheduleBtn.title = "AI automatically re-assigns scheduled dates for overdue & unscheduled tasks";
    aiRescheduleBtn.addEventListener("click", async () => {
      if (this.isProcessingAI)
        return;
      this.isProcessingAI = true;
      new import_obsidian3.Notice("\u{1F916} AI is rescheduling tasks...");
      aiRescheduleBtn.text = "\u23F3 Rescheduling...";
      try {
        const tasks = this.taskService.getAllTasks();
        const newSchedules = await this.aiService.rescheduleTasks(tasks);
        let count = 0;
        for (const [taskId, newDate] of Object.entries(newSchedules)) {
          const target = tasks.find((t) => t.id === taskId);
          if (target) {
            await this.taskService.updateTaskSchedule(target.file, newDate);
            count++;
          }
        }
        new import_obsidian3.Notice(`\u2728 AI rescheduled ${count} tasks!`);
      } catch (e) {
        console.error(e);
        new import_obsidian3.Notice("\u274C Failed to AI reschedule tasks.");
      } finally {
        this.isProcessingAI = false;
        this.render();
      }
    });
    const searchInput = controlsEl.createEl("input", {
      type: "text",
      placeholder: "Filter tasks...",
      value: this.searchFilter,
      cls: "jira-tm-search-input"
    });
    searchInput.addEventListener("input", (e) => {
      this.searchFilter = e.target.value;
      this.renderBoard(boardEl);
    });
    const refreshBtn = controlsEl.createEl("button", {
      text: "Refresh",
      cls: "jira-tm-btn-secondary"
    });
    refreshBtn.addEventListener("click", () => this.render());
    const boardEl = container.createDiv({ cls: "jira-board-container" });
    this.renderBoard(boardEl);
  }
  renderBoard(boardEl) {
    boardEl.empty();
    const allTasks = this.taskService.getAllTasks();
    const filteredTasks = allTasks.filter((t) => {
      if (!this.searchFilter)
        return true;
      const query = this.searchFilter.toLowerCase();
      return t.title.toLowerCase().includes(query) || t.id.toLowerCase().includes(query);
    });
    if (this.activeViewMode === "status") {
      this.renderStatusBoard(boardEl, filteredTasks, allTasks);
    } else {
      this.renderScheduleBoard(boardEl, filteredTasks);
    }
  }
  renderStatusBoard(boardEl, tasks, allTasks) {
    const columns = [
      { status: "todo", title: "TO DO" },
      { status: "in_progress", title: "IN PROGRESS" },
      { status: "done", title: "DONE" }
    ];
    const rootTasks = tasks.filter((t) => !t.parent || !allTasks.some((p) => p.id === t.parent));
    for (const col of columns) {
      const colTasks = rootTasks.filter((t) => t.status === col.status);
      const colEl = boardEl.createDiv({ cls: "jira-column" });
      colEl.dataset.status = col.status;
      const colHeader = colEl.createDiv({ cls: "jira-column-header" });
      colHeader.createEl("span", { text: col.title, cls: "jira-column-title" });
      colHeader.createEl("span", {
        text: `${colTasks.length}`,
        cls: "jira-column-count"
      });
      const cardList = colEl.createDiv({ cls: "jira-card-list" });
      cardList.addEventListener("dragover", (e) => {
        e.preventDefault();
        cardList.addClass("jira-drag-over");
      });
      cardList.addEventListener("dragleave", () => {
        cardList.removeClass("jira-drag-over");
      });
      cardList.addEventListener("drop", async (e) => {
        var _a;
        e.preventDefault();
        cardList.removeClass("jira-drag-over");
        const filePath = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
        if (filePath) {
          const targetTask = tasks.find((t) => t.file.path === filePath);
          if (targetTask && targetTask.status !== col.status) {
            await this.taskService.updateTaskStatus(targetTask.file, col.status);
            this.render();
          }
        }
      });
      for (const task of colTasks) {
        const subtasks = allTasks.filter((t) => t.parent === task.id);
        this.renderCard(cardList, task, subtasks);
      }
    }
  }
  renderScheduleBoard(boardEl, tasks) {
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const tomorrow = /* @__PURE__ */ new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    const tomorrowStr = tomorrow.toISOString().split("T")[0];
    const columns = [
      {
        key: "overdue",
        title: "OVERDUE",
        filter: (t) => t.status !== "done" && t.scheduled && t.scheduled < todayStr
      },
      {
        key: "today",
        title: "TODAY",
        filter: (t) => t.scheduled === todayStr
      },
      {
        key: "tomorrow",
        title: "TOMORROW",
        filter: (t) => t.scheduled === tomorrowStr
      },
      {
        key: "later",
        title: "LATER / UNSCHEDULED",
        filter: (t) => !t.scheduled || t.scheduled > tomorrowStr && t.status !== "done"
      }
    ];
    for (const col of columns) {
      const colTasks = tasks.filter(col.filter);
      const colEl = boardEl.createDiv({ cls: "jira-column" });
      colEl.dataset.scheduleKey = col.key;
      const colHeader = colEl.createDiv({ cls: "jira-column-header" });
      colHeader.createEl("span", { text: col.title, cls: "jira-column-title" });
      colHeader.createEl("span", {
        text: `${colTasks.length}`,
        cls: "jira-column-count"
      });
      const cardList = colEl.createDiv({ cls: "jira-card-list" });
      for (const task of colTasks) {
        this.renderCard(cardList, task, []);
      }
    }
  }
  renderCard(parentEl, task, subtasks) {
    const cardEl = parentEl.createDiv({ cls: "jira-task-card" });
    cardEl.draggable = true;
    cardEl.addEventListener("dragstart", (e) => {
      if (e.dataTransfer) {
        e.dataTransfer.setData("text/plain", task.file.path);
      }
    });
    const cardHeader = cardEl.createDiv({ cls: "jira-card-card-header" });
    const idBadge = cardHeader.createEl("span", { cls: "jira-card-id", text: task.id });
    idBadge.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.taskService.openTaskNote(task.file);
    });
    if (task.scheduled) {
      cardHeader.createEl("span", {
        cls: "jira-card-date",
        text: `\u{1F4C5} ${task.scheduled}`
      });
    }
    cardEl.createDiv({ cls: "jira-card-title", text: task.title });
    if (subtasks.length > 0) {
      const subtasksContainer = cardEl.createDiv({ cls: "jira-subtasks-container" });
      subtasksContainer.createDiv({
        cls: "jira-subtasks-header",
        text: `Subtasks (${subtasks.filter((s) => s.status === "done").length}/${subtasks.length})`
      });
      const subtaskListEl = subtasksContainer.createDiv({ cls: "jira-subtask-list" });
      for (const sub of subtasks) {
        const subRow = subtaskListEl.createDiv({ cls: "jira-subtask-row" });
        const chk = subRow.createEl("input", {
          type: "checkbox",
          cls: "jira-subtask-chk"
        });
        chk.checked = sub.status === "done";
        chk.addEventListener("change", async (e) => {
          e.stopPropagation();
          const newStatus = chk.checked ? "done" : "todo";
          await this.taskService.updateTaskStatus(sub.file, newStatus);
          this.render();
        });
        const subTitle = subRow.createEl("span", {
          cls: `jira-subtask-title ${sub.status === "done" ? "is-done" : ""}`,
          text: `${sub.id}: ${sub.title}`
        });
        subTitle.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.taskService.openTaskNote(sub.file);
        });
      }
    }
    const subtaskInputRow = cardEl.createDiv({ cls: "jira-subtask-input-row hidden" });
    const subInput = subtaskInputRow.createEl("input", {
      type: "text",
      placeholder: "Subtask title...",
      cls: "jira-subtask-input"
    });
    const submitSub = async () => {
      const val = subInput.value.trim();
      if (val) {
        subInput.value = "";
        await this.taskService.createSubtask(task, val);
        this.render();
      }
    };
    subInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submitSub();
      }
    });
    const footerEl = cardEl.createDiv({ cls: "jira-card-footer" });
    const priorityBadge = footerEl.createEl("span", {
      cls: `jira-priority-badge priority-${task.priority}`,
      text: task.priority.toUpperCase()
    });
    const actionEl = footerEl.createDiv({ cls: "jira-card-actions" });
    const addSubBtn = actionEl.createEl("button", {
      text: "+ Subtask",
      cls: "jira-action-btn"
    });
    addSubBtn.title = "Add child TODO";
    addSubBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      subtaskInputRow.toggleClass("hidden", false);
      subInput.focus();
    });
    const aiBtn = actionEl.createEl("button", {
      text: "\u2728 AI",
      cls: "jira-action-btn jira-ai-btn"
    });
    aiBtn.title = "AI automatically breaks down this task into subtasks";
    aiBtn.addEventListener("click", async (e) => {
      e.stopPropagation();
      if (this.isProcessingAI)
        return;
      this.isProcessingAI = true;
      aiBtn.text = "\u23F3";
      new import_obsidian3.Notice(`\u{1F916} AI is breaking down "${task.title}"...`);
      try {
        const subtaskTitles = await this.aiService.breakdownTask(task);
        for (const subTitle of subtaskTitles) {
          await this.taskService.createSubtask(task, subTitle);
        }
        new import_obsidian3.Notice(`\u2728 Created ${subtaskTitles.length} subtasks with AI!`);
      } catch (err) {
        console.error(err);
        new import_obsidian3.Notice("\u274C AI Breakdown failed.");
      } finally {
        this.isProcessingAI = false;
        this.render();
      }
    });
    if (task.status !== "todo") {
      const prevBtn = actionEl.createEl("button", { text: "\u25C0", cls: "jira-action-btn" });
      prevBtn.title = "Move Back";
      prevBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        const prevStatus = task.status === "done" ? "in_progress" : "todo";
        await this.taskService.updateTaskStatus(task.file, prevStatus);
        this.render();
      });
    }
    if (task.status !== "done") {
      const nextBtn = actionEl.createEl("button", { text: "\u25B6", cls: "jira-action-btn" });
      nextBtn.title = "Move Forward";
      nextBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        const nextStatus = task.status === "todo" ? "in_progress" : "done";
        await this.taskService.updateTaskStatus(task.file, nextStatus);
        this.render();
      });
    }
    cardEl.addEventListener("click", async () => {
      await this.taskService.openTaskNote(task.file);
    });
  }
};

// src/main.ts
var TaskManagerPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_TASK_MANAGER,
      (leaf) => new TaskManagerView(leaf, this)
    );
    this.addRibbonIcon("kanban", "Open Task Manager (JIRA)", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-jira-task-manager",
      name: "Open JIRA Task Manager",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new TaskManagerSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TASK_MANAGER)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_TASK_MANAGER,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
