/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TaskManagerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  taskFolder: "tasks",
  idPrefix: "TASK-",
  defaultStatus: "todo",
  defaultPriority: "medium",
  antigravityCommand: "agy",
  customTaskRules: "1. Break down into 15-30 minute physical actions.\n2. Begin with concrete verbs (e.g. 'Open', 'Write', 'Search').\n3. Prohibit vague words like 'Consider', 'Investigate', 'Coordinate'.",
  customRuleFilePath: ""
};

// src/settings.ts
var import_obsidian = require("obsidian");
var TaskManagerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "JIRA-style Task Manager Settings" });
    new import_obsidian.Setting(containerEl).setName("Task Folder").setDesc("Folder path where 1-task-1-note files are stored (e.g. 'tasks').").addText(
      (text) => text.setPlaceholder("tasks").setValue(this.plugin.settings.taskFolder).onChange(async (value) => {
        this.plugin.settings.taskFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("ID Prefix").setDesc("Prefix used when generating new ticket IDs (e.g. 'TASK-').").addText(
      (text) => text.setPlaceholder("TASK-").setValue(this.plugin.settings.idPrefix).onChange(async (value) => {
        this.plugin.settings.idPrefix = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "AI Scrum Master & Physical Action Rules" });
    new import_obsidian.Setting(containerEl).setName("Custom Task Rules (Prompt Rules)").setDesc("Direct prompt instructions injected into AI when generating or breaking down tasks.").addTextArea(
      (text) => text.setPlaceholder("Enter rules for AI...").setValue(this.plugin.settings.customTaskRules).onChange(async (value) => {
        this.plugin.settings.customTaskRules = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Rule File Path in Vault (Optional)").setDesc("Relative path to a Markdown file in your vault containing task rules (e.g. 'templates/task-rules.md').").addText(
      (text) => text.setPlaceholder("templates/task-rules.md").setValue(this.plugin.settings.customRuleFilePath).onChange(async (value) => {
        this.plugin.settings.customRuleFilePath = value.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "AI Engine Settings" });
    new import_obsidian.Setting(containerEl).setName("Antigravity Command").setDesc("Executable name or path for Antigravity CLI (default: 'agy').").addText(
      (text) => text.setPlaceholder("agy").setValue(this.plugin.settings.antigravityCommand).onChange(async (value) => {
        this.plugin.settings.antigravityCommand = value.trim() || "agy";
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/views/TaskManagerView.ts
var import_obsidian6 = require("obsidian");

// src/services/TaskService.ts
var import_obsidian2 = require("obsidian");
var TaskService = class {
  constructor(app, plugin) {
    this.app = app;
    this.plugin = plugin;
  }
  /**
   * Get all task notes inside configured folder or vault
   */
  getAllTasks() {
    const folderPath = (0, import_obsidian2.normalizePath)(this.plugin.settings.taskFolder);
    const files = this.app.vault.getMarkdownFiles();
    const tasks = [];
    for (const file of files) {
      if (folderPath && folderPath !== "." && folderPath !== "/") {
        if (!file.path.startsWith(folderPath + "/") && file.path !== folderPath) {
          continue;
        }
      }
      const cache = this.app.metadataCache.getFileCache(file);
      const fm = (cache == null ? void 0 : cache.frontmatter) || {};
      const title = fm.title || file.basename;
      const id = fm.id || file.basename;
      const status = this.normalizeStatus(fm.status);
      const priority = this.normalizePriority(fm.priority);
      tasks.push({
        id,
        title,
        status,
        priority,
        type: fm.type || (fm.parent ? "subtask" : "task"),
        parent: fm.parent || void 0,
        due: fm.due || void 0,
        scheduled: fm.scheduled || void 0,
        assignee: fm.assignee || "",
        epic: fm.epic || "",
        created: fm.created || "",
        updated: fm.updated || "",
        file
      });
    }
    return tasks;
  }
  /**
   * Recursively get all descendant tasks (subtasks, sub-subtasks, etc.) for a root task
   */
  getTaskSubtree(rootTaskId) {
    const allTasks = this.getAllTasks();
    const result = [];
    const traverse = (parentId, currentDepth) => {
      const children = allTasks.filter((t) => t.parent === parentId);
      for (const child of children) {
        result.push({ task: child, depth: currentDepth });
        traverse(child.id, currentDepth + 1);
      }
    };
    traverse(rootTaskId, 1);
    return result;
  }
  /**
   * Generate collision-free ASCII ID and filename: Prefix + Timestamp + Jitter
   * Example: TASK-20260808225340-a8f3
   */
  generateUniqueId() {
    const prefix = this.plugin.settings.idPrefix || "TASK-";
    const now = /* @__PURE__ */ new Date();
    const timestamp = now.toISOString().replace(/[-T:]/g, "").slice(0, 14);
    const jitter = Math.random().toString(36).substring(2, 6).toLowerCase();
    return `${prefix}${timestamp}-${jitter}`;
  }
  /**
   * Create a new Task note with standard Frontmatter
   */
  async createTask(title, status = "todo", priority = "medium", options) {
    const folderPath = (0, import_obsidian2.normalizePath)(this.plugin.settings.taskFolder);
    if (folderPath && folderPath !== "." && folderPath !== "/") {
      const folder = this.app.vault.getAbstractFileByPath(folderPath);
      if (!folder) {
        await this.app.vault.createFolder(folderPath);
      }
    }
    const idStr = this.generateUniqueId();
    const fileName = `${idStr}.md`;
    const filePath = folderPath && folderPath !== "." && folderPath !== "/" ? `${folderPath}/${fileName}` : fileName;
    const now = (/* @__PURE__ */ new Date()).toISOString();
    const taskType = (options == null ? void 0 : options.type) || ((options == null ? void 0 : options.parent) ? "subtask" : "task");
    const frontmatterLines = [
      "---",
      `id: ${idStr}`,
      `title: "${title.replace(/"/g, '\\"')}"`,
      `status: ${status}`,
      `priority: ${priority}`,
      `type: ${taskType}`
    ];
    if (options == null ? void 0 : options.parent)
      frontmatterLines.push(`parent: "${options.parent}"`);
    if (options == null ? void 0 : options.due)
      frontmatterLines.push(`due: "${options.due}"`);
    if (options == null ? void 0 : options.scheduled)
      frontmatterLines.push(`scheduled: "${options.scheduled}"`);
    frontmatterLines.push(
      `created: ${now}`,
      `updated: ${now}`,
      "---",
      "",
      `# ${title}`,
      "",
      "## Description",
      ""
    );
    const newFile = await this.app.vault.create(filePath, frontmatterLines.join("\n"));
    return newFile;
  }
  /**
   * Convenient wrapper to create a subtask under a parent task or subtask
   */
  async createSubtask(parentTask, title) {
    return this.createTask(title, "todo", "medium", {
      parent: parentTask.id,
      type: "subtask",
      due: parentTask.due,
      scheduled: parentTask.scheduled
    });
  }
  /**
   * Create a subtask under a specific parent ID string
   */
  async createSubtaskByParentId(parentId, title) {
    const allTasks = this.getAllTasks();
    const parentTask = allTasks.find((t) => t.id === parentId);
    return this.createTask(title, "todo", "medium", {
      parent: parentId,
      type: "subtask",
      due: parentTask == null ? void 0 : parentTask.due,
      scheduled: parentTask == null ? void 0 : parentTask.scheduled
    });
  }
  /**
   * Update task status in Frontmatter
   */
  async updateTaskStatus(file, status) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      fm.status = status;
      fm.updated = (/* @__PURE__ */ new Date()).toISOString();
    });
  }
  /**
   * Update scheduled date and due date
   */
  async updateTaskSchedule(file, scheduled, due) {
    await this.app.fileManager.processFrontMatter(file, (fm) => {
      if (scheduled !== void 0)
        fm.scheduled = scheduled;
      if (due !== void 0)
        fm.due = due;
      fm.updated = (/* @__PURE__ */ new Date()).toISOString();
    });
  }
  /**
   * Open the task Markdown note in workspace
   */
  async openTaskNote(file) {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.openFile(file);
  }
  normalizeStatus(status) {
    if (typeof status === "string") {
      const s = status.toLowerCase();
      if (s === "in_progress" || s === "in progress" || s === "doing")
        return "in_progress";
      if (s === "done" || s === "completed")
        return "done";
    }
    return "todo";
  }
  normalizePriority(priority) {
    if (typeof priority === "string") {
      const p = priority.toLowerCase();
      if (p === "low")
        return "low";
      if (p === "high")
        return "high";
      if (p === "highest")
        return "highest";
    }
    return "medium";
  }
};

// src/services/AIService.ts
var import_child_process = require("child_process");
var import_util = require("util");
var os = __toESM(require("os"));
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var import_obsidian3 = require("obsidian");

// src/prompts/systemRules.ts
function getBaseSystemRules() {
  return `\u3010AI\u30B9\u30AF\u30E9\u30E0\u30DE\u30B9\u30BF\u30FC \u7D76\u5BFE\u9075\u5B88\u30EB\u30FC\u30EB\u3011
1. \u3010\u65E5\u672C\u8A9E\u51FA\u529B\u306E\u7D76\u5BFE\u5F37\u5236\u3011:
   - \u751F\u6210\u30FB\u51FA\u529B\u3059\u308B\u3059\u3079\u3066\u306E\u30BF\u30B9\u30AF\u30BF\u30A4\u30C8\u30EB\u3001\u30B5\u30D6\u30BF\u30B9\u30AF\u540D\u3001\u304A\u3088\u3073\u89E3\u8AAC\u6587\u306F\u3001\u5FC5\u305A\u81EA\u7136\u306A\u65E5\u672C\u8A9E\u3067\u8A18\u8FF0\u3057\u3066\u304F\u3060\u3055\u3044\u3002\u82F1\u8A9E\u3067\u306E\u51FA\u529B\u306F\u7981\u6B62\u3067\u3059\u3002

2. \u301015\u301C30\u5206 Next Physical Action (\u5177\u4F53\u7684\u7269\u7406\u884C\u52D5) \u3078\u306E\u5F37\u5236\u5206\u89E3\u3011:
   - \u3059\u3079\u3066\u306E\u30BF\u30B9\u30AF/\u30B5\u30D6\u30BF\u30B9\u30AF\u306F\u300115\u301C30\u5206\u4EE5\u5185\u3067\u7D42\u308F\u308B\u6700\u5C0F\u9650\u306E\u884C\u52D5\u5358\u4F4D\u306B\u5206\u89E3\u3057\u3066\u304F\u3060\u3055\u3044\u3002
   - \u30BF\u30A4\u30C8\u30EB\u306E\u52D5\u8A5E\u306F\u3001\u4EBA\u9593\u304C\u5373\u5EA7\u306B\u4F53\u3092\u52D5\u304B\u305B\u308B\u300C\u5177\u4F53\u7684\u7269\u7406\u884C\u52D5\u300D\u3067\u59CB\u3081\u3066\u304F\u3060\u3055\u3044\u3002
     (\u4F8B: \u300C\u301C\u306E\u753B\u9762\u3092\u958B\u304F\u300D\u300C\u301C\u306E\u30D5\u30A1\u30A4\u30EB\u30921\u884C\u4F5C\u6210\u3059\u308B\u300D\u300C\u301C\u306EURL\u3092\u30D6\u30E9\u30A6\u30B6\u3067\u691C\u7D22\u3059\u308B\u300D\u300C\u301C\u3092\u5165\u529B\u3059\u308B\u300D)

3. \u3010\u62BD\u8C61\u7684\u30FB\u66D6\u6627\u306A\u8868\u73FE\u306E\u7D76\u5BFE\u7981\u6B62\u3011:
   - \u4EE5\u4E0B\u306E\u62BD\u8C61\u7684\u30FB\u66D6\u6627\u306A\u8A00\u8449\u3092\u30BF\u30B9\u30AF\u540D\u306B\u4F7F\u7528\u3059\u308B\u3053\u3068\u3092\u56FA\u304F\u7981\u6B62\u3057\u307E\u3059\u3002
     \xD7 \u7981\u6B62\u8A9E: \u300C\u691C\u8A0E\u3059\u308B\u300D\u300C\u8ABF\u6574\u3059\u308B\u300D\u300C\u8ABF\u67FB\u3059\u308B\u300D\u300C\u78BA\u8A8D\u3059\u308B\u300D\u300C\u5BFE\u5FDC\u3059\u308B\u300D\u300C\u5B9F\u65BD\u3059\u308B\u300D\u300C\u8003\u3048\u308B\u300D\u300C\u628A\u63E1\u3059\u308B\u300D\u300C\u9032\u3081\u308B\u300D
   - \u4E0A\u8A18\u306E\u3088\u3046\u306A\u66D6\u6627\u306A\u4F5C\u696D\u306F\u3001\u5FC5\u305A\u300C\u3069\u3053\u3092\u958B\u304D\u3001\u4F55\u3092\u5165\u529B/\u66F8\u304F\u304B\u300D\u3068\u3044\u3046\u5177\u4F53\u884C\u52D5\u306B\u843D\u3068\u3057\u8FBC\u3093\u3067\u304F\u3060\u3055\u3044\u3002
`;
}
function buildFullSystemRules(customSettingsPrompt, vaultRuleContent) {
  const rules = [getBaseSystemRules()];
  if (customSettingsPrompt == null ? void 0 : customSettingsPrompt.trim()) {
    rules.push(`\u3010\u30E6\u30FC\u30B6\u30FC\u5B9A\u7FA9\u30AB\u30B9\u30BF\u30E0\u30EB\u30FC\u30EB (\u8A2D\u5B9A\u753B\u9762)\u3011:
${customSettingsPrompt.trim()}`);
  }
  if (vaultRuleContent == null ? void 0 : vaultRuleContent.trim()) {
    rules.push(`\u3010\u30E6\u30FC\u30B6\u30FC\u5B9A\u7FA9\u30AB\u30B9\u30BF\u30E0\u30EB\u30FC\u30EB (Vault\u5185\u30D5\u30A1\u30A4\u30EB)\u3011:
${vaultRuleContent.trim()}`);
  }
  return rules.join("\n\n");
}

// src/prompts/taskBreakdownPrompt.ts
function buildTaskBreakdownPrompt(task, customSettingsPrompt, vaultRuleContent) {
  const systemRules = buildFullSystemRules(customSettingsPrompt, vaultRuleContent);
  return `\u3042\u306A\u305F\u306FAI\u30B9\u30AF\u30E9\u30E0\u30DE\u30B9\u30BF\u30FC\u3067\u3059\u3002
\u89AA\u30BF\u30B9\u30AF\u300C${task.title}\u300D\u3092\u300115\u301C30\u5206\u3067\u5B9F\u884C\u53EF\u80FD\u306A3\u301C5\u500B\u306E\u5177\u4F53\u7684\u7269\u7406\u884C\u52D5\uFF08Next Physical Action\uFF09\u306E\u30B5\u30D6\u30BF\u30B9\u30AF\u306B\u5206\u89E3\u3057\u3066\u304F\u3060\u3055\u3044\u3002

${systemRules}

\u3010\u51FA\u529B\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u306E\u5F37\u5236\u3011:
\u4EE5\u4E0B\u306E\u5F62\u5F0F\u306E\u6709\u52B9\u306AJSON\u914D\u5217\uFF08\u6587\u5B57\u5217\u306E\u914D\u5217\uFF09\u306E\u307F\u3092\u51FA\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002
\u5FC5\u305A\u3059\u3079\u3066\u65E5\u672C\u8A9E\u3067\u51FA\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002JSON\u306E\u5916\u5074\u306B\u306F\u8AAC\u660E\u6587\u3084Markdown\u30B3\u30FC\u30C9\u30D6\u30ED\u30C3\u30AF\u3092\u4E00\u5207\u542B\u3081\u306A\u3044\u3067\u304F\u3060\u3055\u3044\u3002

\u4F8B:
["Chrome\u3092\u958B\u3044\u3066\u516C\u5F0F\u30C9\u30AD\u30E5\u30E1\u30F3\u30C8URL\u306B\u30A2\u30AF\u30BB\u30B9\u3059\u308B", "\u30A8\u30C7\u30A3\u30BF\u3092\u958B\u304Dsrc/main.ts\u306E1\u884C\u76EE\u306B\u30B3\u30E1\u30F3\u30C8\u3092\u66F8\u304F", "\u30BF\u30FC\u30DF\u30CA\u30EB\u3092\u958B\u304Dnpm run test\u30B3\u30DE\u30F3\u30C9\u3092\u5B9F\u884C\u3059\u308B"]`;
}

// src/prompts/taskRefinePrompt.ts
function buildTaskRefinePrompt(rootTask, subtree, instruction, customSettingsPrompt, vaultRuleContent) {
  const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const systemRules = buildFullSystemRules(customSettingsPrompt, vaultRuleContent);
  const treeLines = [
    `- ${rootTask.id}: ${rootTask.title} [\u30B9\u30C6\u30FC\u30BF\u30B9: ${rootTask.status}, \u5B9F\u65BD\u4E88\u5B9A\u65E5: ${rootTask.scheduled || "\u672A\u8A2D\u5B9A"}]`
  ];
  for (const node of subtree) {
    const indent = "  ".repeat(node.depth);
    treeLines.push(
      `${indent}- ${node.task.id}: ${node.task.title} (\u89AAID: ${node.task.parent}) [\u30B9\u30C6\u30FC\u30BF\u30B9: ${node.task.status}, \u5B9F\u65BD\u4E88\u5B9A\u65E5: ${node.task.scheduled || "\u672A\u8A2D\u5B9A"}]`
    );
  }
  return `\u3042\u306A\u305F\u306F\u4F34\u8D70\u578B\u306EAI\u30B9\u30AF\u30E9\u30E0\u30DE\u30B9\u30BF\u30FC\u3067\u3059\u3002
\u672C\u65E5\u306E\u65E5\u4ED8: ${todayStr}

${systemRules}

\u3010\u73FE\u5728\u306E\u30BF\u30B9\u30AF\u30FB\u30B5\u30D6\u30BF\u30B9\u30AF\u968E\u5C64\u30C4\u30EA\u30FC\u3011:
${treeLines.join("\n")}

\u3010\u30E6\u30FC\u30B6\u30FC\u304B\u3089\u306E\u58C1\u6253\u3061\u30FB\u4FEE\u6B63\u6307\u793A\u3011:
"${instruction}"

\u6307\u793A\u3092\u5206\u6790\u3057\u3001\u30BF\u30B9\u30AF\u30C4\u30EA\u30FC\u306B\u5BFE\u3059\u308B\u8FFD\u52A0\u30FB\u5909\u66F4\u6848\u3092\u4F5C\u6210\u3057\u3066\u304F\u3060\u3055\u3044\u3002
\u8FFD\u52A0\u30FB\u5909\u66F4\u3059\u308B\u30B5\u30D6\u30BF\u30B9\u30AF\u540D\u306F\u5FC5\u305A15\u301C30\u5206\u3067\u5B8C\u4E86\u3059\u308B\u65E5\u672C\u8A9E\u306E\u5177\u4F53\u7684\u7269\u7406\u884C\u52D5\u306B\u3057\u3066\u304F\u3060\u3055\u3044\u3002

\u3010\u30EC\u30B9\u30DD\u30F3\u30B9\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u306E\u5F37\u5236\u3011:
\u4EE5\u4E0B\u306E\u69CB\u9020\u306B\u4E00\u81F4\u3059\u308B\u6709\u52B9\u306AJSON\u30AA\u30D6\u30B8\u30A7\u30AF\u30C8\u306E\u307F\u3092\u51FA\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002
\u5FC5\u305A\u3059\u3079\u3066\u65E5\u672C\u8A9E\u3067\u8A18\u8FF0\u3057\u3066\u304F\u3060\u3055\u3044\u3002JSON\u306E\u5916\u5074\u306BMarkdown\u30B3\u30FC\u30C9\u30D6\u30ED\u30C3\u30AF\u3084\u8AAC\u660E\u6587\u3092\u4E00\u5207\u542B\u3081\u306A\u3044\u3067\u304F\u3060\u3055\u3044\u3002

{
  "explanation": "\u884C\u3063\u305F\u5909\u66F4\u5185\u5BB9\u306E\u7C21\u6F54\u306A\u8AAC\u660E\uFF08\u65E5\u672C\u8A9E1\u6587\uFF09",
  "subtasksToAdd": [
    { "title": "\u30A8\u30C7\u30A3\u30BF\u3092\u958B\u304D\u8A2D\u5B9A\u30D5\u30A1\u30A4\u30EB\u306E\u8A72\u5F53\u884C\u3092\u7DE8\u96C6\u3059\u308B", "parentId": "${rootTask.id}" }
  ],
  "subtaskIdsToRemove": ["TASK-XXX"],
  "subtaskUpdates": [
    { "id": "TASK-YYY", "title": "\u66F4\u65B0\u5F8C\u306E\u65E5\u672C\u8A9E\u5177\u4F53\u884C\u52D5\u30BF\u30A4\u30C8\u30EB", "scheduled": "${todayStr}" }
  ]
}
\u203B subtasksToAdd \u5185\u306E parentId \u3092\u7701\u7565\u3057\u305F\u5834\u5408\u306F\u3001\u81EA\u52D5\u7684\u306B "${rootTask.id}" \u304C\u89AA\u3068\u306A\u308A\u307E\u3059\u3002`;
}

// src/prompts/taskReschedulePrompt.ts
function buildTaskReschedulePrompt(tasks, customSettingsPrompt, vaultRuleContent) {
  const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const systemRules = buildFullSystemRules(customSettingsPrompt, vaultRuleContent);
  const taskSummaries = tasks.map((t) => ({
    id: t.id,
    title: t.title,
    status: t.status,
    due: t.due || "\u672A\u8A2D\u5B9A",
    scheduled: t.scheduled || "\u672A\u8A2D\u5B9A"
  }));
  return `\u3042\u306A\u305F\u306F\u30B9\u30DE\u30FC\u30C8\u306AAI\u30B9\u30B1\u30B8\u30E5\u30FC\u30EB\u30D1\u30FC\u30C8\u30CA\u30FC\u3067\u3059\u3002
\u672C\u65E5\u306E\u65E5\u4ED8: ${todayStr}

${systemRules}

\u3010\u5206\u6790\u5BFE\u8C61\u30BF\u30B9\u30AF\u4E00\u89A7\u3011:
${JSON.stringify(taskSummaries, null, 2)}

\u671F\u9650\u5207\u308C\uFF08OVERDUE\uFF09\u307E\u305F\u306F\u672A\u30B9\u30B1\u30B8\u30E5\u30FC\u30EB\uFF08UNSCHEDULED\uFF09\u3067\u672A\u5B8C\u4E86\u306E\u30BF\u30B9\u30AF\u306B\u5BFE\u3057\u3066\u3001\u672C\u65E5\uFF08${todayStr}\uFF09\u4EE5\u964D\u306E\u7121\u7406\u306E\u306A\u3044\u304A\u3059\u3059\u3081\u5B9F\u65BD\u4E88\u5B9A\u65E5\uFF08YYYY-MM-DD\uFF09\u3092\u5272\u308A\u632F\u3063\u3066\u304F\u3060\u3055\u3044\u3002

\u3010\u30EC\u30B9\u30DD\u30F3\u30B9\u30D5\u30A9\u30FC\u30DE\u30C3\u30C8\u306E\u5F37\u5236\u3011:
\u30BF\u30B9\u30AFID\u304B\u3089\u65B0\u3057\u3044\u5B9F\u65BD\u4E88\u5B9A\u65E5\u6587\u5B57\u5217\u3078\u306E\u30DE\u30C3\u30D4\u30F3\u30B0\u3092\u8868\u3059\u6709\u52B9\u306AJSON\u30AA\u30D6\u30B8\u30A7\u30AF\u30C8\u306E\u307F\u3092\u51FA\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002

\u4F8B:
{
  "TASK-20260808-a8f3": "${todayStr}"
}
JSON\u306E\u5916\u5074\u306B\u30C6\u30AD\u30B9\u30C8\u3084\u30B3\u30FC\u30C9\u30D6\u30ED\u30C3\u30AF\u3092\u542B\u3081\u306A\u3044\u3067\u304F\u3060\u3055\u3044\u3002`;
}

// src/services/AIService.ts
var execAsync = (0, import_util.promisify)(import_child_process.exec);
function getExtendedEnv() {
  const home = os.homedir();
  const extraPaths = [
    path.join(home, ".local", "bin"),
    path.join(home, ".antigravity", "bin"),
    path.join(home, ".gemini", "antigravity", "bin"),
    "/usr/local/bin",
    "/opt/homebrew/bin",
    "/usr/bin",
    "/bin"
  ];
  const currentPath = process.env.PATH || "";
  const combinedPath = extraPaths.concat(currentPath.split(":")).filter(Boolean);
  const uniquePath = Array.from(new Set(combinedPath)).join(":");
  return {
    ...process.env,
    PATH: uniquePath
  };
}
function resolveCommandPath(command) {
  if (path.isAbsolute(command)) {
    return command;
  }
  const home = os.homedir();
  const searchDirs = [
    path.join(home, ".local", "bin"),
    path.join(home, ".antigravity", "bin"),
    path.join(home, ".gemini", "antigravity", "bin"),
    "/usr/local/bin",
    "/opt/homebrew/bin",
    "/usr/bin",
    "/bin"
  ];
  for (const dir of searchDirs) {
    const fullPath = path.join(dir, command);
    if (fs.existsSync(fullPath)) {
      return fullPath;
    }
  }
  return command;
}
var AIService = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  /**
   * Retrieve custom rule contents from vault file if specified
   */
  async getVaultRuleContent() {
    var _a;
    const rulePath = (_a = this.plugin.settings.customRuleFilePath) == null ? void 0 : _a.trim();
    if (!rulePath)
      return void 0;
    try {
      const file = this.plugin.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(rulePath));
      if (file && file instanceof import_obsidian3.TFile) {
        return await this.plugin.app.vault.read(file);
      }
    } catch (e) {
      console.warn("[TaskManager AI] Could not read rule file from vault:", e);
    }
    return void 0;
  }
  /**
   * Refine full task hierarchy (parent, subtasks, sub-subtasks) with user instruction
   */
  async refineTaskWithTree(rootTask, subtree, instruction) {
    const vaultRule = await this.getVaultRuleContent();
    const prompt = buildTaskRefinePrompt(
      rootTask,
      subtree,
      instruction,
      this.plugin.settings.customTaskRules,
      vaultRule
    );
    try {
      const output = await this.runCLI(prompt);
      const parsed = this.extractJSONObject(output);
      if (parsed) {
        const rawToAdd = parsed.subtasksToAdd || [];
        const normalizedToAdd = rawToAdd.map((item) => {
          if (typeof item === "string") {
            return { title: item, parentId: rootTask.id };
          }
          return { title: item.title, parentId: item.parentId || rootTask.id };
        });
        return {
          explanation: parsed.explanation || "\u30BF\u30B9\u30AF\u69CB\u9020\u3092\u65E5\u672C\u8A9E\u306E\u5177\u4F53\u7684\u7269\u7406\u884C\u52D5\u306B\u66F4\u65B0\u3057\u307E\u3057\u305F\u3002",
          subtasksToAdd: normalizedToAdd,
          subtaskIdsToRemove: parsed.subtaskIdsToRemove || [],
          subtaskUpdates: parsed.subtaskUpdates || []
        };
      }
    } catch (err) {
      console.warn("[TaskManager AI] Refine CLI failed, using smart fallback:", err);
    }
    return {
      explanation: `\u6307\u793A\u306B\u57FA\u3065\u304D\u65E5\u672C\u8A9E\u306E\u7269\u7406\u884C\u52D5\u30BF\u30B9\u30AF\u3092\u8FFD\u52A0\u3057\u307E\u3057\u305F: "${instruction}"`,
      subtasksToAdd: [{ title: `\u30CE\u30FC\u30C8\u3092\u958B\u304D\u300C${instruction}\u300D\u306E\u30E1\u30E2\u30921\u884C\u4F5C\u6210\u3059\u308B`, parentId: rootTask.id }],
      subtaskIdsToRemove: [],
      subtaskUpdates: []
    };
  }
  /**
   * Ask AI (Antigravity CLI) to break down a parent task into subtask titles
   */
  async breakdownTask(task) {
    const vaultRule = await this.getVaultRuleContent();
    const prompt = buildTaskBreakdownPrompt(
      task,
      this.plugin.settings.customTaskRules,
      vaultRule
    );
    try {
      const output = await this.runCLI(prompt);
      const parsed = this.extractJSONArray(output);
      if (parsed && parsed.length > 0) {
        return parsed;
      }
    } catch (err) {
      console.warn("[TaskManager AI] CLI execution failed, using fallback:", err);
    }
    return [
      `\u30CE\u30FC\u30C8\u3092\u958B\u304D\u300C${task.title}\u300D\u306E\u30A2\u30A6\u30C8\u30E9\u30A4\u30F3\u30921\u884C\u66F8\u304F`,
      `\u30D6\u30E9\u30A6\u30B6\u3092\u958B\u304D\u300C${task.title}\u300D\u306E\u95A2\u9023\u8CC7\u6599\u3092\u691C\u7D22\u3059\u308B`,
      `\u30BF\u30FC\u30DF\u30CA\u30EB\u3092\u958B\u304D\u5B9F\u884C\u30ED\u30B0\u3092\u78BA\u8A8D\u3059\u308B`
    ];
  }
  /**
   * Ask AI (Antigravity CLI) to reschedule overdue/unscheduled tasks
   */
  async rescheduleTasks(tasks) {
    const vaultRule = await this.getVaultRuleContent();
    const prompt = buildTaskReschedulePrompt(
      tasks,
      this.plugin.settings.customTaskRules,
      vaultRule
    );
    try {
      const output = await this.runCLI(prompt);
      const parsed = this.extractJSONObject(output);
      if (parsed && Object.keys(parsed).length > 0) {
        return parsed;
      }
    } catch (err) {
      console.warn("[TaskManager AI] CLI execution failed, using fallback:", err);
    }
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const result = {};
    for (const t of tasks) {
      if (t.status !== "done" && (!t.scheduled || t.scheduled < todayStr)) {
        result[t.id] = todayStr;
      }
    }
    return result;
  }
  async runCLI(promptText) {
    const commandName = this.plugin.settings.antigravityCommand || "agy";
    const exePath = resolveCommandPath(commandName);
    const env = getExtendedEnv();
    const escapedPrompt = promptText.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/`/g, "\\`");
    const cmd = `"${exePath}" -p "${escapedPrompt}"`;
    const { stdout } = await execAsync(cmd, {
      env,
      timeout: 25e3,
      maxBuffer: 1024 * 1024 * 5
    });
    return stdout.trim();
  }
  extractJSONArray(text) {
    try {
      const match = text.match(/\[[\s\S]*\]/);
      if (match) {
        const jsonStr = match[0];
        const arr = JSON.parse(jsonStr);
        if (Array.isArray(arr)) {
          return arr.map((item) => String(item));
        }
      }
    } catch (e) {
      console.error("[TaskManager AI] Failed to parse JSON array:", text);
    }
    return null;
  }
  extractJSONObject(text) {
    try {
      const match = text.match(/\{[\s\S]*\}/);
      if (match) {
        const jsonStr = match[0];
        const obj = JSON.parse(jsonStr);
        if (typeof obj === "object" && obj !== null) {
          return obj;
        }
      }
    } catch (e) {
      console.error("[TaskManager AI] Failed to parse JSON object:", text);
    }
    return null;
  }
};

// src/services/UndoService.ts
var import_obsidian4 = require("obsidian");
var UndoService = class {
  constructor(app) {
    this.app = app;
    this.historyStack = [];
    this.maxHistory = 10;
  }
  /**
   * Record current states of tasks before AI modification
   */
  recordSnapshot(description, targetTasks) {
    const snapshots = targetTasks.map((t) => ({
      filePath: t.file.path,
      title: t.title,
      status: t.status,
      priority: t.priority,
      parent: t.parent,
      scheduled: t.scheduled,
      due: t.due,
      isNewFile: false
    }));
    const actionSnapshot = {
      timestamp: (/* @__PURE__ */ new Date()).toISOString(),
      description,
      snapshots,
      createdFilePaths: []
    };
    this.historyStack.push(actionSnapshot);
    if (this.historyStack.length > this.maxHistory) {
      this.historyStack.shift();
    }
    return actionSnapshot;
  }
  /**
   * Register newly created file paths during this action (for full rollback)
   */
  registerCreatedFile(actionSnapshot, filePath) {
    actionSnapshot.createdFilePaths.push(filePath);
  }
  /**
   * Check if undo is available
   */
  canUndo() {
    return this.historyStack.length > 0;
  }
  /**
   * Perform Rollback (Undo) of the last AI action
   */
  async undo() {
    const action = this.historyStack.pop();
    if (!action)
      return null;
    for (const filePath of action.createdFilePaths) {
      const file = this.app.vault.getAbstractFileByPath(filePath);
      if (file && file instanceof import_obsidian4.TFile) {
        await this.app.vault.delete(file);
      }
    }
    for (const snap of action.snapshots) {
      const file = this.app.vault.getAbstractFileByPath(snap.filePath);
      if (file && file instanceof import_obsidian4.TFile) {
        await this.app.fileManager.processFrontMatter(file, (fm) => {
          fm.title = snap.title;
          fm.status = snap.status;
          fm.priority = snap.priority;
          if (snap.parent !== void 0)
            fm.parent = snap.parent;
          else
            delete fm.parent;
          if (snap.scheduled !== void 0)
            fm.scheduled = snap.scheduled;
          else
            delete fm.scheduled;
          if (snap.due !== void 0)
            fm.due = snap.due;
          else
            delete fm.due;
          fm.updated = (/* @__PURE__ */ new Date()).toISOString();
        });
      }
    }
    return action.description;
  }
};

// src/views/AICopilotModal.ts
var import_obsidian5 = require("obsidian");
var AICopilotModal = class extends import_obsidian5.Modal {
  constructor(app, task, aiService, taskService, undoService, onApplied) {
    super(app);
    this.task = task;
    this.aiService = aiService;
    this.taskService = taskService;
    this.undoService = undoService;
    this.onApplied = onApplied;
    this.pendingResult = null;
    this.chatHistory = [];
    this.isLoading = false;
    this.subtree = [];
    this.subtree = this.taskService.getTaskSubtree(task.id);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("jira-ai-copilot-modal");
    this.renderModal();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  renderModal() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", {
      text: `\u2728 AI Copilot: ${this.task.id} ${this.task.title}`,
      cls: "jira-modal-title"
    });
    const currentTreeBox = contentEl.createDiv({ cls: "jira-modal-tree-box" });
    currentTreeBox.createDiv({
      cls: "jira-modal-box-label",
      text: `Current Subtask Hierarchy Tree (${this.subtree.length} descendant tasks):`
    });
    if (this.subtree.length === 0) {
      currentTreeBox.createEl("p", {
        text: "No subtasks yet. Ask AI to break it down!",
        cls: "jira-modal-empty-text"
      });
    } else {
      const treeContainer = currentTreeBox.createDiv({ cls: "jira-modal-tree-container" });
      for (const node of this.subtree) {
        const indentPx = (node.depth - 1) * 20;
        const rowEl = treeContainer.createDiv({ cls: "jira-modal-tree-row" });
        rowEl.style.paddingLeft = `${indentPx}px`;
        const dateInfo = node.task.scheduled ? ` [\u{1F4C5} ${node.task.scheduled}]` : "";
        const parentInfo = node.depth > 1 ? ` (Parent: ${node.task.parent})` : "";
        rowEl.createEl("span", {
          cls: "jira-tree-bullet",
          text: node.depth > 1 ? "\u2514\u2500 " : "\u251C\u2500 "
        });
        rowEl.createEl("span", {
          cls: "jira-tree-text",
          text: `${node.task.id}: ${node.task.title}${parentInfo}${dateInfo}`
        });
      }
    }
    const quickBar = contentEl.createDiv({ cls: "jira-modal-quick-bar" });
    quickBar.createDiv({ cls: "jira-modal-box-label", text: "Quick One-Tap Instructions:" });
    const quickButtons = [
      { label: "\u{1F50D} Breakdown Subtasks", prompt: "Break down this task and its subtasks into 3-5 detailed technical action items." },
      { label: "\u{1F4C5} Optimize Schedule", prompt: "Schedule all subtasks and sub-subtasks starting from today evenly across upcoming days." },
      { label: "\u{1F9EA} Add Testing Steps", prompt: "Add concrete testing and verification subtasks under the relevant parent task." }
    ];
    for (const q of quickButtons) {
      const btn = quickBar.createEl("button", { text: q.label, cls: "jira-quick-btn" });
      btn.addEventListener("click", () => this.handleInstruction(q.prompt));
    }
    if (this.chatHistory.length > 0) {
      const chatBox = contentEl.createDiv({ cls: "jira-modal-chat-box" });
      for (const msg of this.chatHistory) {
        const msgEl = chatBox.createDiv({
          cls: `jira-chat-msg msg-${msg.sender}`
        });
        msgEl.createEl("span", {
          cls: "msg-role",
          text: msg.sender === "user" ? "\u{1F464} You: " : "\u{1F916} AI: "
        });
        msgEl.createEl("span", { text: msg.text });
      }
    }
    if (this.pendingResult) {
      const previewBox = contentEl.createDiv({ cls: "jira-modal-diff-preview" });
      previewBox.createDiv({
        cls: "jira-modal-box-label",
        text: `Proposed Changes: ${this.pendingResult.explanation}`
      });
      if (this.pendingResult.subtasksToAdd.length > 0) {
        const addSec = previewBox.createDiv({ cls: "jira-diff-section diff-add" });
        addSec.createEl("strong", { text: "\u2795 Tasks to Create:" });
        const ul = addSec.createEl("ul");
        for (const item of this.pendingResult.subtasksToAdd) {
          const pText = item.parentId ? ` (under ${item.parentId})` : "";
          ul.createEl("li", { text: `${item.title}${pText}` });
        }
      }
      if (this.pendingResult.subtaskUpdates.length > 0) {
        const updateSec = previewBox.createDiv({ cls: "jira-diff-section diff-update" });
        updateSec.createEl("strong", { text: "\u270F\uFE0F Tasks to Update:" });
        const ul = updateSec.createEl("ul");
        for (const u of this.pendingResult.subtaskUpdates) {
          ul.createEl("li", { text: `${u.id}: ${u.title || "keep title"} ${u.scheduled ? `(Scheduled: ${u.scheduled})` : ""}` });
        }
      }
      const applyBar = previewBox.createDiv({ cls: "jira-modal-apply-bar" });
      const applyBtn = applyBar.createEl("button", {
        text: "\u2705 Apply Changes to Vault",
        cls: "mod-cta jira-apply-btn"
      });
      applyBtn.addEventListener("click", () => this.applyChanges());
    }
    const formEl = contentEl.createDiv({ cls: "jira-modal-form" });
    const inputEl = formEl.createEl("input", {
      type: "text",
      placeholder: this.isLoading ? "AI is thinking..." : "Type instruction (e.g. 'Add a subtask for TASK-002')...",
      cls: "jira-modal-input"
    });
    inputEl.disabled = this.isLoading;
    const sendBtn = formEl.createEl("button", {
      text: this.isLoading ? "\u23F3" : "Send \u{1F4AC}",
      cls: "jira-modal-send-btn"
    });
    sendBtn.disabled = this.isLoading;
    const submit = () => {
      const text = inputEl.value.trim();
      if (text && !this.isLoading) {
        this.handleInstruction(text);
      }
    };
    sendBtn.addEventListener("click", submit);
    inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter")
        submit();
    });
  }
  async handleInstruction(instruction) {
    this.isLoading = true;
    this.chatHistory.push({ sender: "user", text: instruction });
    this.renderModal();
    try {
      this.subtree = this.taskService.getTaskSubtree(this.task.id);
      const result = await this.aiService.refineTaskWithTree(
        this.task,
        this.subtree,
        instruction
      );
      this.pendingResult = result;
      this.chatHistory.push({ sender: "ai", text: result.explanation });
    } catch (e) {
      console.error(e);
      new import_obsidian5.Notice("\u274C Failed to communicate with AI.");
    } finally {
      this.isLoading = false;
      this.renderModal();
    }
  }
  async applyChanges() {
    if (!this.pendingResult)
      return;
    const allSubtreeTasks = this.subtree.map((n) => n.task);
    const snapshot = this.undoService.recordSnapshot(
      `AI Refine Tree on ${this.task.id}`,
      [this.task, ...allSubtreeTasks]
    );
    for (const req of this.pendingResult.subtasksToAdd) {
      const targetParentId = req.parentId || this.task.id;
      const newFile = await this.taskService.createSubtaskByParentId(targetParentId, req.title);
      this.undoService.registerCreatedFile(snapshot, newFile.path);
    }
    const allTasks = this.taskService.getAllTasks();
    for (const u of this.pendingResult.subtaskUpdates) {
      const target = allTasks.find((s) => s.id === u.id);
      if (target) {
        if (u.scheduled !== void 0) {
          await this.taskService.updateTaskSchedule(target.file, u.scheduled);
        }
        if (u.status !== void 0) {
          await this.taskService.updateTaskStatus(target.file, u.status);
        }
      }
    }
    new import_obsidian5.Notice("\u2728 AI changes applied successfully!");
    this.onApplied();
    this.close();
  }
};

// src/views/TaskManagerView.ts
var VIEW_TYPE_TASK_MANAGER = "jira-task-manager-view";
var TaskManagerView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.searchFilter = "";
    this.activeViewMode = "status";
    this.eventListeners = [];
    this.isProcessingAI = false;
    this.taskService = new TaskService(this.app, this.plugin);
    this.aiService = new AIService(this.plugin);
    this.undoService = new UndoService(this.app);
  }
  getViewType() {
    return VIEW_TYPE_TASK_MANAGER;
  }
  getDisplayText() {
    return "Task Manager (JIRA)";
  }
  getIcon() {
    return "kanban";
  }
  async onOpen() {
    this.render();
    const ref1 = this.app.vault.on("modify", () => this.render());
    const ref2 = this.app.vault.on("create", () => this.render());
    const ref3 = this.app.vault.on("delete", () => this.render());
    const ref4 = this.app.metadataCache.on("changed", () => this.render());
    this.eventListeners.push(ref1, ref2, ref3, ref4);
  }
  async onClose() {
    for (const ref of this.eventListeners) {
      this.app.vault.offref(ref);
      this.app.metadataCache.offref(ref);
    }
    this.eventListeners = [];
  }
  render() {
    const container = this.containerEl;
    container.empty();
    container.addClass("jira-task-manager-container");
    const headerEl = container.createDiv({ cls: "jira-tm-header" });
    const titleGroup = headerEl.createDiv({ cls: "jira-tm-title-group" });
    titleGroup.createEl("h2", { text: "JIRA Task Board" });
    const switcherEl = titleGroup.createDiv({ cls: "jira-view-switcher" });
    const statusTab = switcherEl.createEl("button", {
      text: "Status Board",
      cls: `jira-tab-btn ${this.activeViewMode === "status" ? "active" : ""}`
    });
    statusTab.addEventListener("click", () => {
      this.activeViewMode = "status";
      this.render();
    });
    const scheduleTab = switcherEl.createEl("button", {
      text: "Schedule Board",
      cls: `jira-tab-btn ${this.activeViewMode === "schedule" ? "active" : ""}`
    });
    scheduleTab.addEventListener("click", () => {
      this.activeViewMode = "schedule";
      this.render();
    });
    const createForm = headerEl.createDiv({ cls: "jira-tm-create-form" });
    const titleInput = createForm.createEl("input", {
      type: "text",
      placeholder: "What needs to be done?...",
      cls: "jira-tm-input"
    });
    const createBtn = createForm.createEl("button", {
      text: "+ Create Task",
      cls: "mod-cta jira-tm-btn"
    });
    const submitTask = async () => {
      const text = titleInput.value.trim();
      if (!text)
        return;
      titleInput.value = "";
      const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
      await this.taskService.createTask(text, "todo", "medium", { scheduled: todayStr });
      this.render();
    };
    createBtn.addEventListener("click", submitTask);
    titleInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        submitTask();
      }
    });
    const controlsEl = headerEl.createDiv({ cls: "jira-tm-controls" });
    if (this.undoService.canUndo()) {
      const undoBtn = controlsEl.createEl("button", {
        text: "\u21A9\uFE0F Undo AI Action",
        cls: "jira-tm-btn-undo"
      });
      undoBtn.title = "Revert last AI changes to original state";
      undoBtn.addEventListener("click", async () => {
        const desc = await this.undoService.undo();
        if (desc) {
          new import_obsidian6.Notice(`\u21A9\uFE0F Undone: ${desc}`);
        }
        this.render();
      });
    }
    const aiRescheduleBtn = controlsEl.createEl("button", {
      text: "\u{1F504} AI Reschedule",
      cls: "jira-tm-btn-ai"
    });
    aiRescheduleBtn.title = "AI automatically re-assigns scheduled dates for overdue & unscheduled tasks";
    aiRescheduleBtn.addEventListener("click", async () => {
      if (this.isProcessingAI)
        return;
      this.isProcessingAI = true;
      new import_obsidian6.Notice("\u{1F916} AI is rescheduling tasks...");
      aiRescheduleBtn.text = "\u23F3 Rescheduling...";
      try {
        const tasks = this.taskService.getAllTasks();
        this.undoService.recordSnapshot("AI Reschedule", tasks);
        const newSchedules = await this.aiService.rescheduleTasks(tasks);
        let count = 0;
        for (const [taskId, newDate] of Object.entries(newSchedules)) {
          const target = tasks.find((t) => t.id === taskId);
          if (target) {
            await this.taskService.updateTaskSchedule(target.file, newDate);
            count++;
          }
        }
        new import_obsidian6.Notice(`\u2728 AI rescheduled ${count} tasks!`);
      } catch (e) {
        console.error(e);
        new import_obsidian6.Notice("\u274C Failed to AI reschedule tasks.");
      } finally {
        this.isProcessingAI = false;
        this.render();
      }
    });
    const searchInput = controlsEl.createEl("input", {
      type: "text",
      placeholder: "Filter tasks...",
      value: this.searchFilter,
      cls: "jira-tm-search-input"
    });
    searchInput.addEventListener("input", (e) => {
      this.searchFilter = e.target.value;
      this.renderBoard(boardEl);
    });
    const refreshBtn = controlsEl.createEl("button", {
      text: "Refresh",
      cls: "jira-tm-btn-secondary"
    });
    refreshBtn.addEventListener("click", () => this.render());
    const boardEl = container.createDiv({ cls: "jira-board-container" });
    this.renderBoard(boardEl);
  }
  renderBoard(boardEl) {
    boardEl.empty();
    const allTasks = this.taskService.getAllTasks();
    const filteredTasks = allTasks.filter((t) => {
      if (!this.searchFilter)
        return true;
      const query = this.searchFilter.toLowerCase();
      return t.title.toLowerCase().includes(query) || t.id.toLowerCase().includes(query);
    });
    if (this.activeViewMode === "status") {
      this.renderStatusBoard(boardEl, filteredTasks, allTasks);
    } else {
      this.renderScheduleBoard(boardEl, filteredTasks);
    }
  }
  renderStatusBoard(boardEl, tasks, allTasks) {
    const columns = [
      { status: "todo", title: "TO DO" },
      { status: "in_progress", title: "IN PROGRESS" },
      { status: "done", title: "DONE" }
    ];
    const rootTasks = tasks.filter((t) => !t.parent || !allTasks.some((p) => p.id === t.parent));
    for (const col of columns) {
      const colTasks = rootTasks.filter((t) => t.status === col.status);
      const colEl = boardEl.createDiv({ cls: "jira-column" });
      colEl.dataset.status = col.status;
      const colHeader = colEl.createDiv({ cls: "jira-column-header" });
      colHeader.createEl("span", { text: col.title, cls: "jira-column-title" });
      colHeader.createEl("span", {
        text: `${colTasks.length}`,
        cls: "jira-column-count"
      });
      const cardList = colEl.createDiv({ cls: "jira-card-list" });
      cardList.addEventListener("dragover", (e) => {
        e.preventDefault();
        cardList.addClass("jira-drag-over");
      });
      cardList.addEventListener("dragleave", () => {
        cardList.removeClass("jira-drag-over");
      });
      cardList.addEventListener("drop", async (e) => {
        var _a;
        e.preventDefault();
        cardList.removeClass("jira-drag-over");
        const filePath = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
        if (filePath) {
          const targetTask = tasks.find((t) => t.file.path === filePath);
          if (targetTask && targetTask.status !== col.status) {
            await this.taskService.updateTaskStatus(targetTask.file, col.status);
            this.render();
          }
        }
      });
      for (const task of colTasks) {
        this.renderCard(cardList, task, allTasks);
      }
    }
  }
  renderScheduleBoard(boardEl, tasks) {
    const todayStr = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
    const tomorrow = /* @__PURE__ */ new Date();
    tomorrow.setDate(tomorrow.getDate() + 1);
    const tomorrowStr = tomorrow.toISOString().split("T")[0];
    const columns = [
      {
        key: "overdue",
        title: "OVERDUE",
        filter: (t) => t.status !== "done" && t.scheduled && t.scheduled < todayStr
      },
      {
        key: "today",
        title: "TODAY",
        filter: (t) => t.scheduled === todayStr
      },
      {
        key: "tomorrow",
        title: "TOMORROW",
        filter: (t) => t.scheduled === tomorrowStr
      },
      {
        key: "later",
        title: "LATER / UNSCHEDULED",
        filter: (t) => !t.scheduled || t.scheduled > tomorrowStr && t.status !== "done"
      }
    ];
    for (const col of columns) {
      const colTasks = tasks.filter(col.filter);
      const colEl = boardEl.createDiv({ cls: "jira-column" });
      colEl.dataset.scheduleKey = col.key;
      const colHeader = colEl.createDiv({ cls: "jira-column-header" });
      colHeader.createEl("span", { text: col.title, cls: "jira-column-title" });
      colHeader.createEl("span", {
        text: `${colTasks.length}`,
        cls: "jira-column-count"
      });
      const cardList = colEl.createDiv({ cls: "jira-card-list" });
      for (const task of colTasks) {
        this.renderCard(cardList, task, []);
      }
    }
  }
  renderCard(parentEl, task, allTasks) {
    const cardEl = parentEl.createDiv({ cls: "jira-task-card" });
    cardEl.draggable = true;
    cardEl.addEventListener("dragstart", (e) => {
      if (e.dataTransfer) {
        e.dataTransfer.setData("text/plain", task.file.path);
      }
    });
    const cardHeader = cardEl.createDiv({ cls: "jira-card-card-header" });
    const idBadge = cardHeader.createEl("span", { cls: "jira-card-id", text: task.id });
    idBadge.addEventListener("click", async (e) => {
      e.stopPropagation();
      await this.taskService.openTaskNote(task.file);
    });
    if (task.scheduled) {
      cardHeader.createEl("span", {
        cls: "jira-card-date",
        text: `\u{1F4C5} ${task.scheduled}`
      });
    }
    cardEl.createDiv({ cls: "jira-card-title", text: task.title });
    const subtree = this.taskService.getTaskSubtree(task.id);
    if (subtree.length > 0) {
      const subtasksContainer = cardEl.createDiv({ cls: "jira-subtasks-container" });
      const doneCount = subtree.filter((s) => s.task.status === "done").length;
      subtasksContainer.createDiv({
        cls: "jira-subtasks-header",
        text: `Subtasks (${doneCount}/${subtree.length})`
      });
      const subtaskListEl = subtasksContainer.createDiv({ cls: "jira-subtask-list" });
      for (const node of subtree) {
        const sub = node.task;
        const indentPx = (node.depth - 1) * 14;
        const subRow = subtaskListEl.createDiv({ cls: "jira-subtask-row" });
        subRow.style.paddingLeft = `${indentPx}px`;
        const chk = subRow.createEl("input", {
          type: "checkbox",
          cls: "jira-subtask-chk"
        });
        chk.checked = sub.status === "done";
        chk.addEventListener("change", async (e) => {
          e.stopPropagation();
          const newStatus = chk.checked ? "done" : "todo";
          await this.taskService.updateTaskStatus(sub.file, newStatus);
          this.render();
        });
        const subTitle = subRow.createEl("span", {
          cls: `jira-subtask-title ${sub.status === "done" ? "is-done" : ""}`,
          text: `${node.depth > 1 ? "\u21B3 " : ""}${sub.id}: ${sub.title}`
        });
        subTitle.addEventListener("click", async (e) => {
          e.stopPropagation();
          await this.taskService.openTaskNote(sub.file);
        });
      }
    }
    const subtaskInputRow = cardEl.createDiv({ cls: "jira-subtask-input-row hidden" });
    const subInput = subtaskInputRow.createEl("input", {
      type: "text",
      placeholder: "Subtask title...",
      cls: "jira-subtask-input"
    });
    const submitSub = async () => {
      const val = subInput.value.trim();
      if (val) {
        subInput.value = "";
        await this.taskService.createSubtask(task, val);
        this.render();
      }
    };
    subInput.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        submitSub();
      }
    });
    const footerEl = cardEl.createDiv({ cls: "jira-card-footer" });
    const priorityBadge = footerEl.createEl("span", {
      cls: `jira-priority-badge priority-${task.priority}`,
      text: task.priority.toUpperCase()
    });
    const actionEl = footerEl.createDiv({ cls: "jira-card-actions" });
    const addSubBtn = actionEl.createEl("button", {
      text: "+ Subtask",
      cls: "jira-action-btn"
    });
    addSubBtn.title = "Add child TODO";
    addSubBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      subtaskInputRow.toggleClass("hidden", false);
      subInput.focus();
    });
    const aiBtn = actionEl.createEl("button", {
      text: "\u2728 AI",
      cls: "jira-action-btn jira-ai-btn"
    });
    aiBtn.title = "Open AI Copilot for interactive wall-striking & task refinement";
    aiBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      const modal = new AICopilotModal(
        this.app,
        task,
        this.aiService,
        this.taskService,
        this.undoService,
        () => this.render()
      );
      modal.open();
    });
    if (task.status !== "todo") {
      const prevBtn = actionEl.createEl("button", { text: "\u25C0", cls: "jira-action-btn" });
      prevBtn.title = "Move Back";
      prevBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        const prevStatus = task.status === "done" ? "in_progress" : "todo";
        await this.taskService.updateTaskStatus(task.file, prevStatus);
        this.render();
      });
    }
    if (task.status !== "done") {
      const nextBtn = actionEl.createEl("button", { text: "\u25B6", cls: "jira-action-btn" });
      nextBtn.title = "Move Forward";
      nextBtn.addEventListener("click", async (e) => {
        e.stopPropagation();
        const nextStatus = task.status === "todo" ? "in_progress" : "done";
        await this.taskService.updateTaskStatus(task.file, nextStatus);
        this.render();
      });
    }
    cardEl.addEventListener("click", async () => {
      await this.taskService.openTaskNote(task.file);
    });
  }
};

// src/main.ts
var TaskManagerPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_TASK_MANAGER,
      (leaf) => new TaskManagerView(leaf, this)
    );
    this.addRibbonIcon("kanban", "Open Task Manager (JIRA)", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-jira-task-manager",
      name: "Open JIRA Task Manager",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new TaskManagerSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_TASK_MANAGER)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({
        type: VIEW_TYPE_TASK_MANAGER,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
